### PR TITLE
update hc-utils method name

### PR DESCRIPTION
**Pull request by JettTech**
### Updates:
 - replaces hc-utils `get_header` with new `get_action` method name
 
 
**NB: Depends on [hc-utils PR #32](https://github.com/holochain/hc-utils/pull/32)**

### CODE REVIEW

**Review by zo-el — CHANGES_REQUESTED** [review]
you need to update the crate to point to a new release

**Comment by JettTech** [comment]
This PR is dependent on [hc utils pr #32](https://github.com/holochain/hc-utils/pull/32) .  Once that pr is merged and released, I will point to that release. :+1:

**Review by zo-el — APPROVED** [review]
pre-approving this before its pointing to the right hc-utils release.. 

Also, I have changed the base to the `v0.0.138` branch which needs to be pushed to develop too. The reason for doing so is that all our DNA's uses git branches for hc-zome-lib

**Comment by JettTech** [comment]
NB: switched base branch back to develop to trigger ci tests.

**Pull request merged**
